### ISSUE TITLE
What a great name for a repo... 🔥🔥🔥

### ISSUE THREAD

**Issue by sjhansen3** [abajcsy/hallucinate#1]

**Comment by sjhansen3** [comment]
Y u no respond @abajcsy. Tagging @eratner cuz he a bro. Press f to pay respects.

**Comment by eratner** [comment]
f

**Comment by abajcsy** [comment]
I got a good laugh out of it during the deadline but also I'm dead inside

**Comment by sjhansen3** [comment]
f
